name: 'Hello World'
description: 'Greet someone and say good luck for Boards'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'Student'
runs:
  using: 'node20'
  main: 'index.js'
